server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**

            - id: patient-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/patients/**

            - id: appointment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/appointments/**

            - id: prescription-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/prescriptions/**
